// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSplitMedia
          tag="Help"
          title="Frequently Asked Questions"
          description="Learn more about how TrabyOS can help you scale your trading workflow."
          items={[
            {
              question: "What markets are supported?",
              answer: "TrabyOS currently supports US equities, crypto markets, and major forex pairs.",
            },
            {
              question: "Is my data secure?",
              answer: "Yes, we use industry-standard encryption to protect your sensitive financial data.",
            },
            {
              question: "Can I integrate my own brokers?",
              answer: "We support integrations with most major retail and institutional brokerage platforms.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/solar-panel-manufacturing-plant-researcher-typing-laptop-keyboard-closeup_482257-123394.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
