// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesBentoGrid from '@/components/sections/features/FeaturesBentoGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesBentoGrid
          tag="Key Benefits"
          title="Designed for active traders"
          description="Professional-grade software built for efficiency, control, and reduced cognitive load."
          features={[
            {
              title: "Contextual Understanding",
              description: "Never lose sight of why a move matters for your specific portfolio.",
              imageSrc: "http://img.b2bpic.net/free-photo/sound-volume-up-front-side-with-white-background_187299-39989.jpg?_wi=2",
            },
            {
              title: "Fragmented Workflows",
              description: "Consolidate your news feeds, charts, and social data into one place.",
              imageSrc: "http://img.b2bpic.net/free-photo/information-improvement-data-report_53876-138583.jpg?_wi=2",
            },
            {
              title: "Decision Efficiency",
              description: "Make better trades in less time with AI-driven summaries.",
              imageSrc: "http://img.b2bpic.net/free-photo/physician-using-blood-pressure-monitor-check-pulse-blood-pressure_482257-112283.jpg?_wi=2",
            },
            {
              title: "Pro-Grade Control",
              description: "The speed and reliability required for active semi-pro trading.",
              imageSrc: "http://img.b2bpic.net/free-photo/person-running-with-stopwatch_1048-1717.jpg?_wi=2",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
