// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardCarousel from '@/components/sections/hero/HeroBillboardCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardCarousel
          tag="Next-Gen Fintech"
          title="Speak to the market. Understand what matters. Act."
          description="TrabyOS is a voice-first interface that connects market movement, understanding, your position, and trading action inside one professional environment."
          primaryButton={{
            text: "Get Early Access",
            href: "#contact",
          }}
          secondaryButton={{
            text: "See How It Works",
            href: "#how-it-works",
          }}
          items={[
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3GLo0YRGGsIy7uNuPUjGzkkSL86/uploaded-1787470309335-6jrlopge.png",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/sound-volume-up-front-side-with-white-background_187299-39989.jpg?_wi=1",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/information-improvement-data-report_53876-138583.jpg?_wi=1",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/physician-using-blood-pressure-monitor-check-pulse-blood-pressure_482257-112283.jpg?_wi=1",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/person-running-with-stopwatch_1048-1717.jpg?_wi=1",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/woman-typing-laptop-sitting-home-with-automation-lighting-system_482257-8729.jpg?_wi=1",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
