/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";

const primaryButton = {
  text: "Get for Mac",
  href: "#contact"
};
const secondaryButton = {
  text: "See How It Works",
  href: "#how-it-works"
};
const items = [
  {
    imageSrc: "https://storage.googleapis.com/webild/users/user_3GLo0YRGGsIy7uNuPUjGzkkSL86/uploaded-1787470309335-6jrlopge.png"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/sound-volume-up-front-side-with-white-background_187299-39989.jpg?_wi=1"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/information-improvement-data-report_53876-138583.jpg?_wi=1"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/physician-using-blood-pressure-monitor-check-pulse-blood-pressure_482257-112283.jpg?_wi=1"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/person-running-with-stopwatch_1048-1717.jpg?_wi=1"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/woman-typing-laptop-sitting-home-with-automation-lighting-system_482257-8729.jpg?_wi=1"
  }
];

type HeroBillboardCarouselProps = {
  tag: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  items: ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never })[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
};

const HeroInline = () => {
  const duplicated = [...items, ...items, ...items, ...items];

  return (
    <section
      aria-label="Hero section"
      className="relative flex flex-col items-center justify-center gap-8 md:gap-10 w-full min-h-svh pt-25 pb-20 md:pt-30"
    >
      <div className="flex flex-col items-center gap-6 w-content-width mx-auto text-center max-w-4xl">
        <span className="px-3.5 py-1.5 rounded-full bg-[var(--background-accent)] text-xs md:text-sm font-medium text-accent tracking-wide uppercase">
          Voice trading interface for Mac
        </span>

        <TextAnimation
          text={"Your voice. Your market. Your move."}
          variant={"slide-up"}
          gradientText={false}
          tag="h1"
          className="text-5xl sm:text-6xl md:text-7xl lg:text-8xl leading-[1.1] font-semibold text-center text-balance text-foreground"
        />

        <TextAnimation
          text={"Understand market moves, review your positions, and prepare trades through conversation."}
          variant={"slide-up"}
          gradientText={false}
          tag="p"
          className="max-w-2xl text-lg md:text-xl lg:text-2xl leading-relaxed text-accent text-balance"
        />

        <div className="flex justify-center mt-2">
          <Button text="Explore the workflow" href="#how-it-works" variant="primary" />
        </div>
      </div>
    </section>
  );
};

export default function HeroSection() {
  return (
    <div data-webild-section="hero" data-section="hero" id="hero">
      <HeroInline />
    </div>
  );
}
