// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "how-it-works" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import { BarChart2, Mic, Zap } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HowItWorksSection(): React.JSX.Element {
  return (
    <div id="how-it-works" data-section="how-it-works">
        <SectionErrorBoundary name="how-it-works">
              <AboutFeaturesSplit
          tag="Voice First"
          title="One workflow for everything"
          description="Stop jumping between disconnected tools. TrabyOS centralizes your charting, news, and execution into a single, cohesive voice-ready environment."
          items={[
            {
              icon: Mic,
              title: "Voice Intelligence",
              description: "Ask natural questions about your positions and market movements.",
            },
            {
              icon: BarChart2,
              title: "Structured Insights",
              description: "Get visual proof points instead of raw data overload.",
            },
            {
              icon: Zap,
              title: "Instant Action",
              description: "Execute trades faster with context-aware command tools.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/woman-typing-laptop-sitting-home-with-automation-lighting-system_482257-8729.jpg?_wi=2"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
