// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "product" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProductSection(): React.JSX.Element {
  return (
    <div id="product" data-section="product">
        <SectionErrorBoundary name="product">
              <FeaturesImageBento
          tag="Visual Interface"
          title="Clarity at every level"
          description="A purpose-built interface that respects your expertise and keeps focus on high-impact market signals."
          items={[
            {
              title: "Dashboard View",
              description: "Your complete workspace",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-code-running-computer-screens-modern-server-room_482257-114724.jpg",
            },
            {
              title: "Market Depth",
              description: "Deeper analysis visuals",
              imageSrc: "http://img.b2bpic.net/free-photo/conceptual-image-showcasing-businessman-digital-environment_482257-127120.jpg",
            },
            {
              title: "Voice Engine",
              description: "Active listening visualizer",
              imageSrc: "http://img.b2bpic.net/free-photo/3d-abstract-soundwaves-background-with-flowing-lines_1048-15842.jpg",
            },
            {
              title: "Mobile Access",
              description: "Trade on the go",
              imageSrc: "http://img.b2bpic.net/free-photo/businessman-working-with-computer-with-coffee-cup-hotel-room_1150-17469.jpg",
            },
            {
              title: "News Feed",
              description: "Real-time context",
              imageSrc: "http://img.b2bpic.net/free-photo/research-agency-office-worker-analyzing-organization-financial-data-statistics-young-confident-company-employee-reviewing-startup-project-status-charts-while-sitting-modern-office_482257-41511.jpg",
            },
            {
              title: "Analytics",
              description: "Performance tracking",
              imageSrc: "http://img.b2bpic.net/free-photo/trading-stock-stock-market-business-graph-trading-investment-broker-stock-exchange-market_169016-66719.jpg",
            },
            {
              title: "Trade Execution",
              description: "One-click action",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-shopping-online_23-2151952964.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
