// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "security" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SecuritySection(): React.JSX.Element {
  return (
    <div id="security" data-section="security">
        <SectionErrorBoundary name="security">
              <MetricsMediaCards
          tag="Trusted Performance"
          title="Institutional grade infrastructure"
          description="Engineered for speed, reliability, and security to match professional standards."
          metrics={[
            {
              value: "99.9%",
              title: "Uptime",
              description: "Always available for high-volatility events.",
              imageSrc: "http://img.b2bpic.net/free-photo/market-trends-concept-with-computer_23-2150372439.jpg",
            },
            {
              value: "<20ms",
              title: "Latency",
              description: "Market-leading execution speeds.",
              imageSrc: "http://img.b2bpic.net/free-photo/empty-business-entrepreneur-office-setup-home-with-personal-computer_482257-91126.jpg",
            },
            {
              value: "AES-256",
              title: "Encryption",
              description: "Bank-grade data protection.",
              imageSrc: "http://img.b2bpic.net/free-photo/young-man-works-computer-night_169016-63253.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
