// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialTrustCard from '@/components/sections/testimonial/TestimonialTrustCard';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialTrustCard
          quote="TrabyOS removed all the noise from my trading day. Finally, I have a voice interface that understands my portfolio as well as I do."
          rating={5}
          author="Marcus V., Active Semi-Pro Trader"
          avatars={[
            {
              name: "Marcus",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-smiling-senior-man-holding-smart-phone_23-2147935571.jpg",
            },
            {
              name: "Sarah",
              imageSrc: "http://img.b2bpic.net/free-photo/joyful-freelancer-dressed-casual-t-shirt-sitting-front-laptop-looking-smiling-with-cheerful-expression-after-successful-morning-work-enjoying-sunny-day-outdoor-cafe_273609-6602.jpg",
            },
            {
              name: "David",
              imageSrc: "http://img.b2bpic.net/free-photo/middle-age-businessman-smiling-happy-standing-city_839833-25759.jpg",
            },
            {
              name: "Elena",
              imageSrc: "http://img.b2bpic.net/free-photo/concentrated-young-african-man-sitting-coworking_171337-13496.jpg",
            },
            {
              name: "Tom",
              imageSrc: "http://img.b2bpic.net/free-photo/young-pensive-businessman-classic-black-suit-with-wireless-earphones-dreamily-looking-aside-with-hand-watch-laptop-knees-outdoor_574295-5743.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
